config/routes.rb
Rails.application.routes.draw do
  resources :applications do
    member do
      get :step1
      get :step2
      get :step3
      get :step4
    end
  end
  root 'pages#home'

  get 'about' => 'pages#about'

  get 'options' => 'pages#options'

  get 'partner' => 'pages#partner'

  get 'mobile' => 'pages#mobile'
  
  get 'terms_and_conditions' => 'pages#terms_and_conditions'
  
  get 'privacy_policy' => 'pages#privacy_policy'

end

app/models/application.rb
class Application < ActiveRecord::Base
   attr_accessor :next_step
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_application, only: [:show, :edit, :update, :destroy , :step1,  :step2 , :step3 , :step4 ]

  # GET /applications
  # GET /applications.json
  def index
    @applications = Application.all
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
  end

  # GET /applications/new
  def new
    @step = "step1"
    @next_step = "step2"
    @application = Application.new
  end

  # GET /applications/1/edit
  def edit
    @step = "step1"
    @next_step = "step2"
    render "new"
  end

  def step1
    @step = "step1"
    @next_step = "step2"
    render "new"
  end

  def step2
    @step = "step2"
    @next_step = "step3"
    render "new"
  end

  def step3
    @step = "step3"
    @next_step = "step4"
    render "new"
  end

  def step4
    @step = "step4"
    @next_step = ""
    render "new"
  end
  # POST /applications
  # POST /applications.json
  def create
    @application = Application.new(application_params)

    respond_to do |format|
      if @application.save
        format.html { redirect_to "/applications/#{@application.id}/step2", notice: 'Application was successfully created.' }
        format.json { render :show, status: :created, location: @application }
      else
        format.html { render :new }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        #if blank, send email because step 4 is finished. remove and false when SMTP creds are integrated
        if application_params[:next_step].blank? and false
          UserMailer.notify_feedback(@application).deliver_now
        end

        format.html { redirect_to "/applications/#{@application.id}/#{application_params[:next_step]}", notice: 'Application was successfully updated.' }
        format.json { render :show, status: :ok, location: @application }
      else
        format.html { render :edit }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url, notice: 'Application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_params
      params.require(:application).permit(:next_step, :bizname, :biznamedba, :bizadd, :bizfl, :bizcity, :bizstate, :bizzip, :bizphone, :bizemail, :bizfax, :bizurl, :fundreq, :entity, :cotype, :bizloc, :datestart, :prodoffered, :ticketsale, :moccsales, :mononccsales, :postype, :poscontact, :posswipe, :poskey, :fein, :amex, :fname, :lname, :homeadd, :homefl, :homecity, :homestate, :homezip, :homeemail, :homephone, :creditscore, :ownershipperc, :dob, :ssn, :dl, :bk, :taxlien, :priormca, :mcaprovider, :ref1name, :ref1phone, :ref2name, :ref2phone, :ref3name, :ref3phone, :bankrefname, :bankrefphone, :llmort, :llmortphone, :rent, :current)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def options
  end

  def partner
  end

  def mobile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/applications/_app_header.html.erb
    <div class="container logo">
     <%= image_tag("logo copy.png", size: "auto") %><br><br> 
          <span class="fa fa-phone"></span><span class="phone"> 1-800-PEERPOINT</span><hr>
    
    </div>

app/views/applications/edit.html.erb
<h1>Editing Application</h1>

<%= render 'form' %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Applications</h1>

<table>
  <thead>
    <tr>
      <th>Bizname</th>
      <th>Biznamedba</th>
      <th>Bizadd</th>
      <th>Bizfl</th>
      <th>Bizcity</th>
      <th>Bizstate</th>
      <th>Bizzip</th>
      <th>Bizphone</th>
      <th>Bizemail</th>
      <th>Bizfax</th>
      <th>Bizurl</th>
      <th>Fundreq</th>
      <th>Entity</th>
      <th>Cotype</th>
      <th>Bizloc</th>
      <th>Datestart</th>
      <th>Prodoffered</th>
      <th>Ticketsale</th>
      <th>Moccsales</th>
      <th>Mononccsales</th>
      <th>Postype</th>
      <th>Poscontact</th>
      <th>Posswipe</th>
      <th>Poskey</th>
      <th>Fein</th>
      <th>Amex</th>
      <th>Fname</th>
      <th>Lname</th>
      <th>Homeadd</th>
      <th>Homefl</th>
      <th>Homecity</th>
      <th>Homestate</th>
      <th>Homezip</th>
      <th>Homeemail</th>
      <th>Homephone</th>
      <th>Creditscore</th>
      <th>Ownershipperc</th>
      <th>Dob</th>
      <th>Ssn</th>
      <th>Dl</th>
      <th>Bk</th>
      <th>Taxlien</th>
      <th>Priormca</th>
      <th>Mcaprovider</th>
      <th>Ref1name</th>
      <th>Ref1phone</th>
      <th>Ref2name</th>
      <th>Ref2phone</th>
      <th>Ref3name</th>
      <th>Ref3phone</th>
      <th>Bankrefname</th>
      <th>Bankrefphone</th>
      <th>Llmort</th>
      <th>Llmortphone</th>
      <th>Rent</th>
      <th>Current</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td><%= application.bizname %></td>
        <td><%= application.biznamedba %></td>
        <td><%= application.bizadd %></td>
        <td><%= application.bizfl %></td>
        <td><%= application.bizcity %></td>
        <td><%= application.bizstate %></td>
        <td><%= application.bizzip %></td>
        <td><%= application.bizphone %></td>
        <td><%= application.bizemail %></td>
        <td><%= application.bizfax %></td>
        <td><%= application.bizurl %></td>
        <td><%= application.fundreq %></td>
        <td><%= application.entity %></td>
        <td><%= application.cotype %></td>
        <td><%= application.bizloc %></td>
        <td><%= application.datestart %></td>
        <td><%= application.prodoffered %></td>
        <td><%= application.ticketsale %></td>
        <td><%= application.moccsales %></td>
        <td><%= application.mononccsales %></td>
        <td><%= application.postype %></td>
        <td><%= application.poscontact %></td>
        <td><%= application.posswipe %></td>
        <td><%= application.poskey %></td>
        <td><%= application.fein %></td>
        <td><%= application.amex %></td>
        <td><%= application.fname %></td>
        <td><%= application.lname %></td>
        <td><%= application.homeadd %></td>
        <td><%= application.homefl %></td>
        <td><%= application.homecity %></td>
        <td><%= application.homestate %></td>
        <td><%= application.homezip %></td>
        <td><%= application.homeemail %></td>
        <td><%= application.homephone %></td>
        <td><%= application.creditscore %></td>
        <td><%= application.ownershipperc %></td>
        <td><%= application.dob %></td>
        <td><%= application.ssn %></td>
        <td><%= application.dl %></td>
        <td><%= application.bk %></td>
        <td><%= application.taxlien %></td>
        <td><%= application.priormca %></td>
        <td><%= application.mcaprovider %></td>
        <td><%= application.ref1name %></td>
        <td><%= application.ref1phone %></td>
        <td><%= application.ref2name %></td>
        <td><%= application.ref2phone %></td>
        <td><%= application.ref3name %></td>
        <td><%= application.ref3phone %></td>
        <td><%= application.bankrefname %></td>
        <td><%= application.bankrefphone %></td>
        <td><%= application.llmort %></td>
        <td><%= application.llmortphone %></td>
        <td><%= application.rent %></td>
        <td><%= application.current %></td>
        <td><%= link_to 'Show', application %></td>
        <td><%= link_to 'Edit', edit_application_path(application) %></td>
        <td><%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Application', new_application_path %>

app/views/applications/new.html.erb
<%= render 'app_header' %>

<%= render 'form' %>

<%#= link_to 'Back', applications_path %>

app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bizname:</strong>
  <%= @application.bizname %>
</p>

<p>
  <strong>Biznamedba:</strong>
  <%= @application.biznamedba %>
</p>

<p>
  <strong>Bizadd:</strong>
  <%= @application.bizadd %>
</p>

<p>
  <strong>Bizfl:</strong>
  <%= @application.bizfl %>
</p>

<p>
  <strong>Bizcity:</strong>
  <%= @application.bizcity %>
</p>

<p>
  <strong>Bizstate:</strong>
  <%= @application.bizstate %>
</p>

<p>
  <strong>Bizzip:</strong>
  <%= @application.bizzip %>
</p>

<p>
  <strong>Bizphone:</strong>
  <%= @application.bizphone %>
</p>

<p>
  <strong>Bizemail:</strong>
  <%= @application.bizemail %>
</p>

<p>
  <strong>Bizfax:</strong>
  <%= @application.bizfax %>
</p>

<p>
  <strong>Bizurl:</strong>
  <%= @application.bizurl %>
</p>

<p>
  <strong>Fundreq:</strong>
  <%= @application.fundreq %>
</p>

<p>
  <strong>Entity:</strong>
  <%= @application.entity %>
</p>

<p>
  <strong>Cotype:</strong>
  <%= @application.cotype %>
</p>

<p>
  <strong>Bizloc:</strong>
  <%= @application.bizloc %>
</p>

<p>
  <strong>Datestart:</strong>
  <%= @application.datestart %>
</p>

<p>
  <strong>Prodoffered:</strong>
  <%= @application.prodoffered %>
</p>

<p>
  <strong>Ticketsale:</strong>
  <%= @application.ticketsale %>
</p>

<p>
  <strong>Moccsales:</strong>
  <%= @application.moccsales %>
</p>

<p>
  <strong>Mononccsales:</strong>
  <%= @application.mononccsales %>
</p>

<p>
  <strong>Postype:</strong>
  <%= @application.postype %>
</p>

<p>
  <strong>Poscontact:</strong>
  <%= @application.poscontact %>
</p>

<p>
  <strong>Posswipe:</strong>
  <%= @application.posswipe %>
</p>

<p>
  <strong>Poskey:</strong>
  <%= @application.poskey %>
</p>

<p>
  <strong>Fein:</strong>
  <%= @application.fein %>
</p>

<p>
  <strong>Amex:</strong>
  <%= @application.amex %>
</p>

<p>
  <strong>Fname:</strong>
  <%= @application.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @application.lname %>
</p>

<p>
  <strong>Homeadd:</strong>
  <%= @application.homeadd %>
</p>

<p>
  <strong>Homefl:</strong>
  <%= @application.homefl %>
</p>

<p>
  <strong>Homecity:</strong>
  <%= @application.homecity %>
</p>

<p>
  <strong>Homestate:</strong>
  <%= @application.homestate %>
</p>

<p>
  <strong>Homezip:</strong>
  <%= @application.homezip %>
</p>

<p>
  <strong>Homeemail:</strong>
  <%= @application.homeemail %>
</p>

<p>
  <strong>Homephone:</strong>
  <%= @application.homephone %>
</p>

<p>
  <strong>Creditscore:</strong>
  <%= @application.creditscore %>
</p>

<p>
  <strong>Ownershipperc:</strong>
  <%= @application.ownershipperc %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @application.dob %>
</p>

<p>
  <strong>Ssn:</strong>
  <%= @application.ssn %>
</p>

<p>
  <strong>Dl:</strong>
  <%= @application.dl %>
</p>

<p>
  <strong>Bk:</strong>
  <%= @application.bk %>
</p>

<p>
  <strong>Taxlien:</strong>
  <%= @application.taxlien %>
</p>

<p>
  <strong>Priormca:</strong>
  <%= @application.priormca %>
</p>

<p>
  <strong>Mcaprovider:</strong>
  <%= @application.mcaprovider %>
</p>

<p>
  <strong>Ref1name:</strong>
  <%= @application.ref1name %>
</p>

<p>
  <strong>Ref1phone:</strong>
  <%= @application.ref1phone %>
</p>

<p>
  <strong>Ref2name:</strong>
  <%= @application.ref2name %>
</p>

<p>
  <strong>Ref2phone:</strong>
  <%= @application.ref2phone %>
</p>

<p>
  <strong>Ref3name:</strong>
  <%= @application.ref3name %>
</p>

<p>
  <strong>Ref3phone:</strong>
  <%= @application.ref3phone %>
</p>

<p>
  <strong>Bankrefname:</strong>
  <%= @application.bankrefname %>
</p>

<p>
  <strong>Bankrefphone:</strong>
  <%= @application.bankrefphone %>
</p>

<p>
  <strong>Llmort:</strong>
  <%= @application.llmort %>
</p>

<p>
  <strong>Llmortphone:</strong>
  <%= @application.llmortphone %>
</p>

<p>
  <strong>Rent:</strong>
  <%= @application.rent %>
</p>

<p>
  <strong>Current:</strong>
  <%= @application.current %>
</p>

<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>

app/views/pages/about.html.erb
<div class="about container"> 
    <h1>About Us</h1>
</div><!--container-->

<div class="container aboutus">
    <h2 class="peerway">The PeerPoint Way</h2>
    <p>There's a way we do business that starts with the owner and carries down through every employee at our firm. The principles of Integrity, Knowledge and Reputation guide us in our daily work.</p>
    <p>We realize the proper financing is critical to the health of any small business.  In order to grow, businesses need access to capital to purchase inventory, maintain cash flow, hire new employees, purchase equipment and invest back in the company.  Yet, a landmark study by Harvard Business School shows that bank loan availability to small businesses plummeted during the recession and has stayed at these low levels since.</p>
</div><!--end container-->

<div class="process container">
    <h3 class="peerapp">A New Approah to Business Loans from PeerPoint</h3>
  	<div class="row">
  	<div class="col-md-6">
        <p class="peertext">PeerPoint Capital uses technology to make the small business borrowing process fast and easy.  We deliver loan decisions in minutes and funding as fast as two business days. By focusing on the health of the business rather than your personal credit score, PeerPoint has higher approval rates than most banks.</p>
  	</div>
  	<div class="col-md-6">
  	
  	<ul>
  	<li><span class="fa fa-check-square-o">&nbsp;&nbsp;Most deals approved & funded with 72 hours</span></li>
  	<li><span class="fa fa-check-square-o">&nbsp;&nbsp;Most businesses qualify</span></li>
  	<li><span class="fa fa-check-square-o">&nbsp;&nbsp;No application fees or appraisals needed</span></li>
  	<li><span class="fa fa-check-square-o">&nbsp;&nbsp;Payoff tax liens or buyout a partner</span></li>
  	<li><span class="fa fa-check-square-o">&nbsp;&nbsp;Bad credit is OK</span></li>
  	</ul>
  	</div>
  	    <%= link_to '<button type="button" class="btn btn-lg btn-success">See Our Simple Process in Action</button>'.html_safe, new_application_path %>
  	 	<h2></h2>
  	</div><!--end row--> 
  	
</div><!--end container-->
 <%= render 'layouts/footer' %>

app/views/pages/home.html.erb
<!--main page-->
  
  <div class="mainPage">
  
  <%= render 'layouts/header' %>
  
  
  <!--Banner Section-->
  	<div class="hero">
  		<p>Running a Business is Hard, Funding it Should be EASY!</p>
  	</div>
  	
  	<div class="banner container">
 	
  	<div class="row">
  	<div class="col-md-4 col-md-offset-8">
  	<div class="sidebar">
  		<form>
  			<h3>Find out what your business qualifies for in just seconds</h3><br>
  				<div class="form-group">
    				<label for="exampleInputEmail1">How much would you like to borrow?</label>
    				<select class="form-control">
  						<option>$10,000-$25,000</option>
  						<option>$25,000-$50,000</option>
  						<option>$50,000-75,000</option>
  						<option>$75,000-$100,000</option>
  						<option>$100,000-$500,000</option>
  						<option>$500,000-$1,000,000</option>
					</select>
  				</div>
  				<div class="form-group">
    				<label for="">How soon do you need the money?</label>
    				<select class="form-control">
  						<option>Immediately</option>
  						<option>1 week</option>
  						<option>Next 30 days</option>
  						<option>Over 30 days</option>
					</select>
  				</div>
  				<div class="form-group">
    				<label for="buslength">How old is your business?</label>
    				<select class="form-control">
  						<option>Less than 1 year</option>
  						<option>1-5 years</option>
  						<option>6-10 years</option>
  						<option>10+ years</option>
					</select>
  				</div>
  				<div class="form-group">
    				<label for="exampleInputEmail1">What is your approx. yearly revenue?</label>
    				<select class="form-control">
  						<option>Less than $100,000</option>
  						<option>$100,000-$250,000</option>
  						<option>$250,000-$500,000</option>
  						<option>$500,000-$1,000,000</option>
  						<option>$1,000,000+</option>
					</select>
  				</div>
  	
  				<%= link_to '<button type="button" class="btn btn-lg btn-block">Do I Qualify?</button>'.html_safe, new_application_path %>
  
  		</form> 
  		</div><!--close col-->
  		</div><!--close row-->
  		</div>
  	</div><!--close banner-->
  
  <!--Better Way-->
  
  <div class="betterway container">
  	<h2>A New and Better Way to Fund Your Business</h2>
  	<div class="row">
  		<div class="betterbox col-md-4">
  		  <%= image_tag("step-1.png", size: "120") %>
  			<h4>Fast & Simple Application</h4>
  			<p>The application is simple and only takes a couple minutes.  Our dedicated funding specialists are standing by to help.</p>
  		</div>
  		<div class="betterbox col-md-4">
  		  <%= image_tag("step-2.png", size: "120") %>
  			<h4>Revenue Based Funding</h4>
  			<p>Once approved, you are eligible to receive up to 1.25x your average monthly revenue. It's that simple! </p>
  		</div>
  		<div class="betterbox col-md-4">
  		  <%= image_tag("step-3.png", size: "120") %>
  			<h4>Grow Your Business</h4>
  			<p>Use the funds to...expand your business, buy new equipment, buyout a partner, pay bills, or any other business use.</p>
  		</div>
  	
  	</div>
  </div>
  
  
  <!--
  	<div class="process container">
  	<div class="row">
  	<div class="col-md-6">
  		<video width="400" height="300" src="https://youtu.be/BWew-quWisU" frameborder="0"></video>
  	</div>
  	<div class="col-md-6">
  	<h2>See Our Simple Process...</h2>
  	<ul>
  	<li><span class="fa fa-check-square-o">&nbsp;&nbsp;Most deals approved & funded with 72 hours</span></li>
  	<li><span class="fa fa-check-square-o">&nbsp;&nbsp;Most businesses qualify</span></li>
  	<li><span class="fa fa-check-square-o">&nbsp;&nbsp;No application fees or appraisals needed</span></li>
  	<li><span class="fa fa-check-square-o">&nbsp;&nbsp;Payoff tax liens or buyout a partner</span></li>
  	<li><span class="fa fa-check-square-o">&nbsp;&nbsp;Bad credit is OK</span></li>
  	</ul>
  	</div>
  	 	
  	</div>
  	</div>
  -->
  <!--peerpoint nation-->
  
  <div class="nation">
    <h2>Join the <span class="nationbrand">PeerPoint</span> Nation</h2>
    <p class="nationhero">We are on a Campaign to fund 100 small businesses in the next 100 days.  We will feature each as a case study in upcoming blogs.  Please help us get the word out and recommend your favorite small business!</p>
    <%= image_tag("PPC_hashtag.jpg", size: "100%") %>
    
  </div>
  <!--CTA 1-->
  
  	<div class="cta1 container">
  	<h2>Working Capital at your Fingertips</h2>
  	<p class="cta1hero">The world's fastest and easiest way to get financing to grow your business.  PeerPoint Advance is A-Rated by the Better Business Bureau and has more satisfied small business clients than anyone in the industry!<p>
  		<%= link_to '<button type="button" class="btn btn-lg">APPLY NOW</button>'.html_safe, new_application_path %>
  	</div><!--close cta1-->
  
  <!--Testimonial-->
  	<div class="test container">
  	<h2>Trusted by Hundreds of Small Business Owners</h2>
  	<p class="test1">PeerPoint Advance has funded over $50 million to help local businesses achieve their goals.  PeerPoint Advance is the industry leader in providing business solutions and working capitial online, but don't take our word for it.  Listen to some of our clients tell their stories. </p><br>
  	
  	<div class="row ">
  		<div class="col-md-6"><!--left col-->
  		  <div class="col-md-4">
  		    <%= image_tag("ching hua.jpg", size: "180x120") %> 
  		  </div>
  		  <div class="col-md-8">
  		    <p class="company">Ching Hua Chinese Restaurant</p>
  		    <p class="testtext">Suburban family owned restaurant needed money fast for emergency repairs.  With funds provided in 4 days their diners can now stay cool on hot summer nights.<p>
  		  </div>
  		</div><!--end left col-->
  		
  		<div class="col-md-6"><!--right col-->
  		  <div class="col-md-4">
  		    <%= image_tag("joyce.jpeg", size: "180x120") %> 
  		  </div>
  		  <div class="col-md-8">
  		    <p class="company">Joyce Family Wellness Center</p>
  		    <p class="testtext">Growing doctor's office needed marketing funds to get the word out.  With quick & easy funding, he is now on his way to becoming a household name in the community.<p>
  		  </div>
  		</div>
  	</div><!--end row--><br><br>
  	
  	<div class="row">
  		<div class="col-md-6"><!--left col-->
  		  
  		  <div class="col-md-4">
  		    <%= image_tag("rub.jpg", size: "180x120") %>
  		  </div>  
  		  <div class="col-md-8">  
  		    <p class="company">Rub's BBQ Smokehouse</p>
  		    <p class="testtext">When you make the best BBQ in town its only natural you expand. Having a great funding partner makes this process simple.<p>
  		  </div>
  		  </div>
  		  
  		<div class="col-md-6"><!--right col-->
  		  <div class="col-md-4">
  		    <%= image_tag("bj.jpg", size: "180x120") %> 
  		  </div>
  		  <div class="col-md-8">
  		    <p class="company">BJ's Beauty Supply</p>
  		    <p class="testtext">When the city's only African-Amercian owned beauty supply retailer needed working capital to increase inventory, we made sure her accounts were looking pretty.<p>
  		  </div>
  	</div>
  	</div><!--end row-->
  	<br>
  		<p class="success"><span class="fa fa-chevron-circle-right arrow"></span><%= link_to 'See How Your Company Can Be the Next Success Story!', new_application_path %><span class="fa fa-chevron-circle-left arrow"></span></p>
  	
  </div><!--close container-->
  
  <!--CTA 3-->
  	<div class="cta3">
  		<h2>Seriously...let's get you funded</h2>
  		<p>Have we worn you down yet? If you have made it this far on the page you obviously need our help.  The process is fast and there is a good chance your business will be approved.  Complete this quick form and we'll be able to give you an idea of what we can do to help you.</p>
  		<form>
  			<div class="form-group">
    			<input type="text" class="form-control" id="FullName" placeholder="Full Name">
  			</div>
  			<div class="form-group">
    			<input type="email" class="form-control" id="Email1" placeholder="Email">
  			</div>
  			<div class="form-group">
    			<input type="phone" class="form-control" id="Phone" placeholder="Phone">
  			</div>
  			<%= link_to '<button type="button" class="btn btn-warning btn-lg">APPLY NOW</button>'.html_safe, new_application_path %>
		</form>
  
  	</div><!--close process-->
  	
  <%= render 'layouts/footer' %>
  
  
  
  </div><!--close mainPage-->
  

app/views/pages/mobile.html.erb
<h1>Pages#mobile</h1>
<p>Find me in app/views/pages/mobile.html.erb</p>

app/views/pages/partner.html.erb
<div class="partner container">
    <div class="row">
    <div class="col-md-5">
        <div class="opthero">
        <h1>Come Partner With Us</h1>
        <p>We are specialists in finding the perfect<br>funding solution for your business.</p><br>
        <%= link_to '<button type="button" class="btn btn-lg">Let&#39;s Work Together</button>'.html_safe, new_application_path %>
        </div>
    </div>
</div><!--close row-->
</div><!--container-->

<div class="container parthero">
    <div class="row">
        <div class="col-md-3">
            <%= image_tag("step-1.png", size: "120") %>
            <h3>Brokers</h3>
            <p class="partco">You're a leasing company, funding advisor or independent sales organization, interested in providing Peerpoint finaincing to your customer</p><br>
            <%= link_to '<button type="button" class="btn btn-primary btn-sm">Learn More</button>'.html_safe, new_application_path %>
        </div>
        <div class="col-md-3">
            <%= image_tag("step-2.png", size: "120") %>
            <h3>Bank Professionals</h3>
            <p class="partco">You're a leasing company, funding advisor or independent sales organization, interested in providing Peerpoint finaincing to your customer</p><br>
            <%= link_to '<button type="button" class="btn btn-primary btn-sm">Learn More</button>'.html_safe, new_application_path %>
        </div>
        <div class="col-md-3">
            <%= image_tag("step-3.png", size: "120") %>
            <h3>Merchant Referral</h3>
            <p class="partco">You're a leasing company, funding advisor or independent sales organization, interested in providing Peerpoint finaincing to your customer</p><br>
            <%= link_to '<button type="button" class="btn btn-primary btn-sm">Learn More</button>'.html_safe, new_application_path %>
        </div>
        <div class="col-md-3">
            <%= image_tag("step-3.png", size: "120") %>
            <h3>Affiliates</h3>
            <p class="partco">You're a leasing company, funding advisor or independent sales organization, interested in providing Peerpoint finaincing to your customer</p><br>
            <%= link_to '<button type="button" class="btn btn-primary btn-sm">Learn More</button>'.html_safe, new_application_path %>
        </div>
        
        
    </div>
    
</div>


<div class="cta3">
  		<h2>Join The PeerPoint Team!</h2>
  		<p>Whether you are looking to for a new funding partner or you want to grow your current business by giving your clients a funding mechanism to pay you, we are the best capital partner you can imagine. Complete this quick form and one of our Business Development Manager will work with you to find a place for you in the PeerPoint Nation.</p>
  		<form>
  			<div class="form-group">
    			<input type="text" class="form-control" id="FullName" placeholder="Full Name">
  			</div>
  			<div class="form-group">
    			<input type="email" class="form-control" id="Email1" placeholder="Email">
  			</div>
  			<div class="form-group">
    			<input type="phone" class="form-control" id="Phone" placeholder="Phone">
  			</div>
  			<%= link_to '<button type="button" class="btn btn-warning btn-lg">APPLY NOW</button>'.html_safe, new_application_path %>
		</form>
  
  	</div>

 <%= render 'layouts/footer' %>